<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LanguageTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</LanguageTargets>
    <Title>TRexIfc</Title>
    <Description>Bitub TRex Dynamo Library, IFC utilities and transformation toolsets</Description>

    <Configurations>Debug;Release;Dev;Test;XbimDev</Configurations>
    <Platforms>AnyCPU</Platforms>
    <RootNamespace>TRex</RootNamespace>
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>
    
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>ManagedMinimumRules.ruleset</CodeAnalysisRuleSet>
    <DocumentationFile>bin\Debug\TRexIfc.xml</DocumentationFile>
  </PropertyGroup>
    
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Dev|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>bin\Dev\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>ManagedMinimumRules.ruleset</CodeAnalysisRuleSet>
    <DocumentationFile>bin\Dev\TRexIfc.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='XbimDev|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>bin\XbimDev\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>ManagedMinimumRules.ruleset</CodeAnalysisRuleSet>
    <DocumentationFile>bin\XbimDev\TRexIfc.xml</DocumentationFile>
  </PropertyGroup>
    
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Test|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>bin\Dev\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>ManagedMinimumRules.ruleset</CodeAnalysisRuleSet>
    <DocumentationFile>bin\Dev\TRexIfc.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>bin\Release\TRexIfc.xml</DocumentationFile>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="DynamoVisualProgramming.DynamoCoreNodes" Version="3.1.0.4724" ExcludeAssets="Runtime"/>
    <PackageReference Include="DynamoVisualProgramming.ZeroTouchLibrary" Version="3.1.0.4724" ExcludeAssets="Runtime"/>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="1.5.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="Xbim.Geometry.Engine.Interop" Version="6.0.0-dev" />
    <PackageReference Include="Bitub.Xbim.Ifc" Version="1.0.24115-XbimDev.20855" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(Configuration)' == 'XbimDev'">
    <PackageReference Include="Xbim.Geometry.Engine.Interop" Version="6.0.0-dev" />
    <PackageReference Include="Bitub.Xbim.Ifc" Version="1.0.24115-XbimDev.20855" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Dev' Or '$(Configuration)' == 'Test'">
    <PackageReference Include="Xbim.Geometry.Engine.Interop" Version="5.1.437" />
    <PackageReference Include="Bitub.Xbim.Ifc" Version="1.0.23114-Dev.29843" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <PackageReference Include="Xbim.Geometry.Engine.Interop" Version="5.1.437" />
    <PackageReference Include="Bitub.Xbim.Ifc" Version="1.0.23114-Dev.29843" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TRexAssimp\TRexAssimp.vcxproj" />
    <ProjectReference Include="..\TRexDynamo\TRexDynamo.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="TRexIfc_DynamoCustomization.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
 
</Project>