# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
   include:
     - dev
     - master
     - xbim-dev
     - feature/*
  paths:
    exclude:
      - .gitignore
      - README.md
      - azure-pipelines.yml
      
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'AnyCPU'
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    buildConfiguration: 'Test'
    buildQualifier: '-Test'
  ${{ elseif eq(variables['Build.SourceBranchName'], 'master') }}: 
    buildConfiguration: 'Release'
    buildQualifier: ''
  ${{ elseif eq(variables['Build.SourceBranchName'], 'dev') }}: 
    buildConfiguration: 'Dev'
    buildQualifier: '-Dev'
  ${{ else }}:
    buildConfiguration: 'Test'
    buildQualifier: '-Test'

steps:
- checkout: self
  persistCredentials: true
  clean: true
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Retrieving stable build number"
      $date=Get-Date
      [int] $buildSecond=[int][Math]::Floor((([int]$date.Hour) * 3600 + ([int]$date.Minute) * 60 + ([int]$date.Second))/2)
      [string] $buildDate=-join($(Get-Date -format yy), ([string]$date.DayOfYear).PadLeft(3,'0'))
      Write-Host "##vso[task.setvariable variable=buildSecond]$buildSecond"
      Write-Host "##vso[task.setvariable variable=buildDate]$buildDate"
      Write-Host "##vso[build.updatebuildnumber]$buildDate.$buildSecond"
      
- task: NuGetToolInstaller@1

- task: NuGetAuthenticate@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    configuration: '$(buildConfiguration)'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'
    
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArchitecture: '$(buildPlatform)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '-t:build -p:Configuration=$(buildConfiguration) -p:BuildMajor=$(majorVersion) -p:BuildMinor=$(minorVersion) -p:BuildRelease=$(buildDate) -p:Build=$(buildSecond) -p:BuildQualifier=$(buildQualifier) -p:DeployDynamoVersion=$(dynamoVersion)'
        
- task: ArchiveFiles@2
  condition: and(succeeded(), in(variables.buildConfiguration, 'Release', 'Dev', 'XbimDev'))
  inputs:
    rootFolderOrFile: 'DeployedPackages/$(dynamoVersion)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/TRex-$(majorVersion).$(minorVersion).$(buildDate)$(buildQualifier).$(buildSecond).zip'
    replaceExistingArchive: true
    verbose: true
    
- task: GitHubRelease@1
  condition: and(succeeded(), in(variables.buildConfiguration, 'Release', 'Dev', 'XbimDev'))
  inputs:
    gitHubConnection: bekraft
    tagSource: 'userSpecifiedTag'
    
    title: 'TRex-$(majorVersion).$(minorVersion).$(buildDate)$(buildQualifier).$(buildSecond)'
    tag: '$(majorVersion).$(minorVersion).$(buildDate)$(buildQualifier).$(buildSecond)'
    assets: '$(Build.ArtifactStagingDirectory)/TRex-$(majorVersion).$(minorVersion).$(buildDate)$(buildQualifier).$(buildSecond).zip'
    
