# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
   include:
     - dev
     - master
     - xbim-dev
     - feature/*
  paths:
    exclude:
      - .gitignore
      - README.md
      - azure-pipelines.yml
      
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    buildConfiguration: 'Test'
    buildQualifier: '-Test'
  ${{ elseif eq(variables['Build.SourceBranchName'], 'master') }}: 
    buildConfiguration: 'Release'
    buildQualifier: ''
  ${{ elseif eq(variables['Build.SourceBranchName'], 'dev') }}: 
    buildConfiguration: 'Dev'
    buildQualifier: '-Dev'
  ${{ elseif eq(variables['Build.SourceBranchName'], 'xbim-dev') }}:
    buildConfiguration: 'XbimDev'
    buildQualifier: '-XbimDev'
  ${{ else }}:
    buildConfiguration: 'Debug'
    buildQualifier: '-Debug'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Retrieving stable build number"
      $date=Get-Date
      [int] $buildSecond=[int][Math]::Floor((([int]$date.Hour) * 3600 + ([int]$date.Minute) * 60 + ([int]$date.Second))/2)
      [string] $buildDate=-join($(Get-Date -format yy), ([string]$date.DayOfYear).PadLeft(3,'0'))
      Write-Host "##vso[task.setvariable variable=buildSecond]$buildSecond"
      Write-Host "##vso[task.setvariable variable=buildDate]$buildDate"
      Write-Host "##vso[build.updatebuildnumber]$buildDate.$buildSecond"
      
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '-p:BuildRelease=$(buildDate) -p:Build=$(buildSecond) -p:BuildQualifier=$(buildQualifier)'
    
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
