<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <RootNamespace>TRex.Tests</RootNamespace>
    <AssemblyName>TRexIfc.Tests</AssemblyName>
    <Title>TRex Tests</Title>
    
    <Configurations>Debug;Release;Dev;Test;XbimDev</Configurations>
    <Platforms>x64</Platforms>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <PlatformTarget>x64</PlatformTarget>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>    
  </PropertyGroup>
      
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <PlatformTarget>x64</PlatformTarget>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
      
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Dev|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Dev\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <PlatformTarget>x64</PlatformTarget>    
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
      
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Test|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Test\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='XbimDev|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\XbimDev\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="DynamoVisualProgramming.DynamoServices" Version="3.5.1.8731" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="Xbim.Geometry.Engine.Interop" Version="6.1.847-netcore" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\TRexAssimp\TRexAssimp.vcxproj" />
    <ProjectReference Include="..\TRexIfc\TRexIfc.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="Resources\extruded-solid.ifc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\IfcSampleHouse.ifc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <TRexAssimpDeployDir>$(SolutionDir)TRexAssimp\x64</TRexAssimpDeployDir>
  </PropertyGroup>

  <Target Name="DeployDependencies" AfterTargets="AfterBuild">
    <Message Importance="High" Text="Deploying native dependencies to $(TargetDir)." />
    
    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
      <SourceDlls Include="$(TRexAssimpDeployDir)\assimp-vc143-mtd.dll;$(TRexAssimpDeployDir)\dracod.dll" />
      <SourcePdbs Include="$(TRexAssimpDeployDir)\assimp-vc143-mtd.pdb;$(TRexAssimpDeployDir)\dracod.pdb" />
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)' != 'Debug'">
      <SourceDlls Include="$(TRexAssimpDeployDir)\assimp-vc143-mt.dll;$(TRexAssimpDeployDir)\draco.dll" />
    </ItemGroup>
    
    <Copy SourceFiles="@(SourceDlls)" DestinationFolder="$(TargetDir)" />
    <Copy SourceFiles="@(SourcePdbs)" DestinationFolder="$(TargetDir)" />
  </Target>
</Project>