<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <!-- <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" /> -->
  <PropertyGroup>
    <LanguageTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</LanguageTargets>

    <Title>TRexIfc UI</Title>
    <OutputType>Library</OutputType>
    <StartupObject />

    <Description>Bitub TRex Dynamo Library, IFC utilities and transformation toolsets</Description>

    <Configurations>Debug;Release;Dev;Test;XbimDev</Configurations>
    <Platforms>AnyCPU</Platforms>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <AssemblyName>TRexIfcUI</AssemblyName>
    <RootNamespace>TRex</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>bin\Debug\TRexIfcUI.xml</DocumentationFile>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Dev|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>bin\Dev\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>bin\Dev\TRexIfcUI.xml</DocumentationFile>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Test|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>bin\Test\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>bin\Dev\TRexIfcUI.xml</DocumentationFile>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>bin\Release\TRexIfcUI.xml</DocumentationFile>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='XbimDev|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>bin\XbimDev\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>bin\XbimDev\TRexIfcUI.xml</DocumentationFile>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DynamoVisualProgramming.Core" Version="3.5.1.8731" ExcludeAssets="Runtime"/>
    <PackageReference Include="DynamoVisualProgramming.WpfUILibrary" Version="3.5.1.8731" ExcludeAssets="Runtime"/>
    <PackageReference Include="DynamoVisualProgramming.ZeroTouchLibrary" Version="3.5.1.8731" ExcludeAssets="Runtime"/>
    <PackageReference Include="Bitub.Xbim.Ifc" Version="1.1.25148-XbimDev.30312" />
    <PackageReference Include="Bitub.Xbim.Ifc.Occt" Version="1.1.25148-XbimDev.30312" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\TRexIfc\TRexIfc.csproj">
      <Project>{2bc161c5-e9f1-4b41-ba92-6dc3d502b00c}</Project>
      <Name>TRexIfc</Name>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="UI\FilterMatchTypeControl.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="UI\CRSTransformControl.xaml.cs">
      <DependentUpon>CRSTransformControl.xaml</DependentUpon>
    </Compile>
    <Compile Update="UI\SceneBuildSettingsControl.xaml.cs">
      <DependentUpon>SceneBuildSettingsControl.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <!-- Local deployment settings and artificact name pattern -->
  <PropertyGroup Condition="'$(Configuration)' != 'Debug'">
    <DeployPath>..\DeployedPackages\$(DeployDynamoVersion)\$(DeployDynamoProjectName)-$(Version)</DeployPath>
  </PropertyGroup>

  <!-- Deployment into Dynamo local path if on debug mode -->
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DeployPath>$(DeployDynamoPath)\$(DeployDynamoProjectName)</DeployPath>
  </PropertyGroup>

  <Target Name="Clean deploy folder of Dynamo App" AfterTargets="Clean">
    <!-- Remove before copying -->
    <Message Importance="High" Text="==> Removing contents from $(DeployPath)." />    
    <RemoveDir Directories="$(DeployPath)" />
  </Target>

  <!-- Deploy Dynamo App to DeployPath and if Debug also to DeployDynamoPath -->
  <Target Name="Deploy Dynamo App" AfterTargets="AfterBuild">
    
    <Message Importance="High" Text="==> Starting deployment to Dynamo `$(DeployDynamoProjectName)` package to `$(DeployPath)`." />
    
    <ItemGroup>
      <NativeDebugDlls Include="$(SolutionDir)TRexAssimp\bin\x64\$(Configuration)\*.dll" />
      <NativeRuntimeDlls Include="$(SolutionDir)TRexAssimp\bin\x64\$(Configuration)\assimp*.dll" />
      <DependencyDlls Include="$(TargetDir)Google*.dll;$(TargetDir)Microsoft*.dll;$(TargetDir)Serilog*.dll;$(TargetDir)SharpGLTF*.dll" />
      <NativeDlls Include="$(TargetDir)win-x64\*.dll" />
      <SourceDlls Include="$(TargetDir)Bitub*.dll;$(TargetDir)TRex*.dll;$(TargetDir)Xbim*.dll;$(TargetDir)Esent*.dll" />
      <SystemDlls Include="$(TargetDir)System*.dll" />
      <SourcePdbs Include="$(TargetDir)*.pdb" />
      <SourceXmls Include="$(TargetDir)*.xml" />
      <SourcePkg Include="pkg.json" />
      <SourceDocs Include="$(SolutionDir)Documentations\*.md" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
      <Message Importance="High" Text="==&gt; Debug Dlls    : `@(NativeDebugDlls)`" />
      <Message Importance="High" Text="==&gt; TRex / Xbim   : `@(SourceDlls)`" />
      <Message Importance="High" Text="==&gt; Dependencies  : `@(DependencyDlls)`" />
      <Message Importance="High" Text="==&gt; XMLs          : `@(SourceXmls)`" />
      <Message Importance="High" Text="==&gt; Native DLLs   : `@(NativeDlls)`" />
    </ItemGroup>

    <!-- Copying to deploy folder if in non-debug mode -->
    <Copy Condition="'$(Configuration)' == 'Debug'" SourceFiles="@(NativeDebugDlls)" DestinationFolder="$(DeployPath)\bin\" />
    <Copy Condition="'$(Configuration)' != 'Debug'" SourceFiles="@(NativeRuntimeDlls)" DestinationFolder="$(DeployPath)\bin\" />
    <Copy SourceFiles="@(DependencyDlls)" DestinationFolder="$(DeployPath)\bin\" />
    <Copy SourceFiles="@(SourceDlls)" DestinationFolder="$(DeployPath)\bin\" />
    <Copy SourceFiles="@(SystemDlls)" DestinationFolder="$(DeployPath)\bin\" />
    <Copy Condition="'$(Configuration)' == 'Debug'" SourceFiles="@(SourcePdbs)" DestinationFolder="$(DeployPath)\bin\" />
    <Copy SourceFiles="@(SourcePkg)" DestinationFolder="$(DeployPath)" />
    <Copy SourceFiles="@(SourceXmls)" DestinationFolder="$(DeployPath)\bin\" />
    <Copy SourceFiles="@(SourceDocs)" DestinationFolder="$(DeployPath)\bin\" />
    <Copy SourceFiles="@(NativeDlls)" DestinationFolder="$(DeployPath)\bin\win10-x64" />
    
    <!-- Set current version -->
    <Exec Command="powershell &quot;((Get-Content -Path $(DeployPath)\@(SourcePkg)) -replace '1.0.0.0','$(FileVersion)') | Set-Content -Path $(DeployPath)\@(SourcePkg) &quot;" Condition="'$(Configuration)' != 'Debug'" />
    
    <Message Importance="High" Text="==> Finalized deployment of `$(DeployDynamoProjectName)` package to `$(DeployPath)`." />
  </Target>
  
  <ItemGroup>
    <_ResxFiles Remove="Properties\Resources.resx" />
  </ItemGroup>

</Project>