using Autodesk.DesignScript.Runtime;

namespace TRex.Export
{
    /// <summary>
    /// Fundamental concept of scaling model unit factor.
    /// </summary>    
    public sealed class UnitScale
    {
        /// <summary>
        /// Given unit factors
        /// </summary>
        [IsVisibleInDynamoLibrary(false)]
        public readonly static UnitScale[] defined =
        {
            new UnitScale { Reference = "m", Name = "Meter", UnitsPerMeter = 1.0f },
            new UnitScale { Reference = "mm", Name = "Millimeter", UnitsPerMeter = 1000.0f },
            new UnitScale { Reference = "cm", Name = "Centimeter", UnitsPerMeter = 100.0f },
            new UnitScale { Reference = "in", Name = "Inch", UnitsPerMeter = 1000.0f / 25.4f }, // 25.4mm per inch
            new UnitScale { Reference = "ft", Name = "Feet", UnitsPerMeter = 1000.0f / (12 * 25.4f) } // 12 inch per foot                                                   
        };

        #region Internals

        private UnitScale()
        {
        }

        #endregion

        /// <summary>
        /// A new unit scale by data.
        /// </summary>
        /// <param name="reference">The short name</param>
        /// <param name="name">The name</param>
        /// <param name="unitsPerMeter">The factor</param>
        /// <returns>New unit scale</returns>
        [IsVisibleInDynamoLibrary(false)]
        public static UnitScale ByData(string reference, string name, float unitsPerMeter)
        {
            return new UnitScale { Reference = reference, Name = name, UnitsPerMeter = unitsPerMeter };
        }

        /// <summary>
        /// Returns a unit factor by given units per meter. <see cref="Reference"/> and <see cref="Name"/> are generated by factor.
        /// </summary>
        /// <param name="unitsPerMeter">The units per meter.</param>
        /// <returns>A compiled unit factor</returns>
        public static UnitScale ByUnitsPerMeter(float unitsPerMeter)
        {
            return new UnitScale { Reference = $"{unitsPerMeter}/m", Name = $"{unitsPerMeter} per meter", UnitsPerMeter = unitsPerMeter };
        }

        /// <summary>
        /// Combines two scales, and inherited model scale and a new nested scale of units per meter.
        /// </summary>
        /// <param name="modelScale">The given model scale</param>
        /// <param name="nestedScale">The intrinsic nested model scale</param>
        /// <returns>A combined unit scale, if nested scale is non-null otherwise the model scale</returns>
        public static UnitScale ByModelUnitScale(UnitScale nestedScale, UnitScale modelScale)
        {
            if (null != nestedScale)
            {
                return new UnitScale
                {
                    Reference = $"{nestedScale.Reference} => {modelScale.Reference}",
                    Name = $"{modelScale.Name} ({nestedScale.Name})",
                    UnitsPerMeter = modelScale.UnitsPerMeter / nestedScale.UnitsPerMeter
                };
            }
            else
            {
                return modelScale;
            }
        }

        /// <summary>
        /// Gets the scale of this unit per meter.
        /// </summary>
        [IsVisibleInDynamoLibrary(false)]
        public float UnitsPerMeter { get; set; }

        /// <summary>
        /// The name of unit.
        /// </summary>
        [IsVisibleInDynamoLibrary(false)]
        public string Name { get; set; }

        /// <summary>
        /// The reference/identifier.
        /// </summary>
        [IsVisibleInDynamoLibrary(false)]
        public string Reference { get; set; }

        public override string ToString()
        {
            return $"{UnitsPerMeter}/E ({Name})";
        }
    }
}
